#priority 0
//This file was created via CT-GUI! Editing it is not advised!
//Don't touch me!
//#Remove
//Don't touch me!
//#Add
recipes.addShaped(<minecraft:shears>, [[null, <minecraft:iron_ingot>, null],[<minecraft:iron_ingot>, null, <minecraft:iron_ingot>], [<minecraft:iron_ingot>, <minecraft:iron_ingot>, null]]);
recipes.addShaped(<minecraft:paper>, [[<minecraft:vine>, <minecraft:vine>, <minecraft:vine>],[<minecraft:vine>, <minecraft:vine>, <minecraft:vine>], [<minecraft:vine>, <minecraft:vine>, <minecraft:vine>]]);
recipes.addShaped(<techguns:fraggrenade>, [[null, <minecraft:stone_button>, null],[<techguns:itemshared:46>, <minecraft:tnt>, <techguns:itemshared:46>], [null, <techguns:itemshared:46>, null]]);
recipes.addShaped(<techguns:stielgranate>, [[<techguns:itemshared:46>, <minecraft:tnt>, <techguns:itemshared:46>],[null, <minecraft:stick>, null], [null, <minecraft:stick>, null]]);
recipes.addShaped(<techguns:pistol>, [[<techguns:itemshared:38>, <techguns:itemshared:50>, <techguns:itemshared:57>],[<techguns:itemshared:50>, <techguns:itemshared:38>, <techguns:itemshared:50>], [<techguns:itemshared:57>, <techguns:itemshared:50>, <techguns:itemshared:34>]]);
recipes.addShaped(<techguns:revolver>, [[<techguns:itemshared:38>, null, null],[null, <techguns:itemshared:38>, <techguns:itemshared:57>], [null, <techguns:itemshared:57>, <techguns:itemshared:34>]]);
recipes.addShaped(<techguns:sawedoff>, [[null, null, null],[null, <techguns:itemshared:57>, <techguns:itemshared:38>], [null, <techguns:itemshared:38>, <techguns:itemshared:33>]]);
recipes.addShaped(<techguns:ballistic_shield>, [[<techguns:itemshared:55>, <techguns:itemshared:50>, null],[<techguns:itemshared:50>, <techguns:itemshared:50>, <techguns:itemshared:34>], [<techguns:itemshared:50>, <techguns:itemshared:50>, null]]);
recipes.addShaped(<techguns:riot_shield>, [[null, <techguns:itemshared:55>, null],[null, <techguns:itemshared:50>, <techguns:itemshared:33>], [null, <techguns:itemshared:55>, null]]);
recipes.addShaped(<techguns:explosive_charge:1>, [[null, <techguns:itemshared:66>, null],[<techguns:itemshared:46>, <techguns:explosive_charge>, <techguns:itemshared:46>], [null, null, null]]);
recipes.addShaped(<techguns:explosive_charge>, [[null, <minecraft:stone_button>, null],[<techguns:itemshared:65>, <minecraft:tnt>, <techguns:itemshared:65>], [<minecraft:tnt>, <minecraft:tnt>, <minecraft:tnt>]]);
recipes.addShaped(<techguns:combatknife>, [[null, null, <techguns:itemshared:83>],[null, <techguns:itemshared:83>, null], [<techguns:itemshared:83>, null, null]]);
recipes.addShaped(<techguns:crowbar>, [[null, null, <minecraft:iron_ingot>],[null, <minecraft:iron_ingot>, null], [<minecraft:iron_ingot>, null, null]]);
recipes.addShaped(<techguns:item_bunkerdoor>, [[<techguns:itemshared:50>, <techguns:itemshared:50>, <techguns:itemshared:50>],[<techguns:itemshared:50>, <techguns:itemshared:50>, <techguns:itemshared:50>], [<techguns:itemshared:50>, <techguns:itemshared:50>, <techguns:itemshared:50>]]);
recipes.addShaped(<techguns:item_door3x3:3>, [[<techguns:itemshared:49>, null, <techguns:itemshared:49>],[<techguns:itemshared:49>, <techguns:itemshared:70>, <techguns:itemshared:49>], [<techguns:itemshared:49>, null, <techguns:itemshared:49>]]);
recipes.addShaped(<techguns:item_door3x3:2>, [[<techguns:itemshared:50>, <techguns:itemshared:50>, <techguns:itemshared:50>],[<techguns:itemshared:50>, <techguns:itemshared:50>, <techguns:itemshared:50>], [null, <techguns:itemshared:70>, null]]);
recipes.addShaped(<techguns:item_door3x3:1>, [[null, <techguns:itemshared:70>, null],[<techguns:itemshared:50>, <techguns:itemshared:50>, <techguns:itemshared:50>], [<techguns:itemshared:50>, <techguns:itemshared:50>, <techguns:itemshared:50>]]);
recipes.addShaped(<techguns:item_door3x3>, [[<techguns:itemshared:46>, null, <techguns:itemshared:46>],[<techguns:itemshared:46>, <techguns:itemshared:70>, <techguns:itemshared:46>], [<techguns:itemshared:46>, null, <techguns:itemshared:46>]]);
recipes.addShaped(<techguns:itemshared:143>, [[null, <techguns:itemshared:144>, <techguns:itemshared:144>],[null, <techguns:itemshared:144>, <techguns:itemshared:144>], [null, <techguns:itemshared:144>, <techguns:itemshared:20>]]);
recipes.addShaped(<techguns:itemshared:132>, [[<minecraft:wool>, <minecraft:wool>, <minecraft:wool>],[<minecraft:wool>, null, <minecraft:wool>], [<minecraft:wool>, null, <minecraft:wool>]]);
recipes.addShaped(<techguns:itemshared:115>, [[null, <techguns:itemshared:111>, <techguns:itemshared:111>],[null, <techguns:itemshared:111>, <techguns:itemshared:111>], [null, null, <techguns:itemshared:14>]]);
recipes.addShaped(<techguns:itemshared:114>, [[<techguns:itemshared:111>, <techguns:itemshared:111>, <techguns:itemshared:111>],[<techguns:itemshared:111>, <techguns:itemshared:18>, <techguns:itemshared:111>], [<techguns:itemshared:111>, <techguns:itemshared:111>, <techguns:itemshared:111>]]);
recipes.addShaped(<techguns:itemshared:116>, [[<techguns:itemshared:111>, <techguns:itemshared:111>, <techguns:itemshared:111>],[<techguns:itemshared:111>, <techguns:itemshared:111>, <techguns:itemshared:111>], [null, null, <techguns:itemshared:16>]]);
recipes.addShaped(<techguns:itemshared:110> * 8, [[null, null, null],[null, <techguns:itemshared:111>, null], [null, null, null]]);
recipes.addShaped(<techguns:itemshared:111>, [[<techguns:itemshared:110>, <techguns:itemshared:110>, <techguns:itemshared:110>],[<techguns:itemshared:110>, null, <techguns:itemshared:110>], [<techguns:itemshared:110>, <techguns:itemshared:110>, <techguns:itemshared:110>]]);
recipes.addShaped(<techguns:itemshared:112>, [[<techguns:itemshared:113>, null, null],[<techguns:itemshared:113>, null, null], [<techguns:itemshared:113>, null, <techguns:itemshared:10>]]);
recipes.addShaped(<techguns:itemshared:113>, [[<techguns:itemshared:109>, <techguns:itemshared:109>, <techguns:itemshared:109>],[<techguns:itemshared:109>, <techguns:itemshared:109>, <techguns:itemshared:109>], [<techguns:itemshared:109>, <techguns:itemshared:109>, <techguns:itemshared:12>]]);
recipes.addShaped(<techguns:itemshared:107>, [[null, <techguns:itemshared:108>, <techguns:itemshared:108>],[null, <techguns:itemshared:108>, <techguns:itemshared:108>], [null, <techguns:itemshared:108>, <techguns:itemshared:20>]]);
recipes.addShaped(<techguns:itemshared:95> * 2, [[<minecraft:log>, <minecraft:log>, null],[<minecraft:log>, <minecraft:log>, null], [null, null, null]]);
furnace.addRecipe(<techguns:itemshared:56>, <techguns:itemshared:55>, 0.0);
furnace.addRecipe(<techguns:itemshared:55>, <techguns:itemshared:96>, 0.0);
furnace.addRecipe(<techguns:itemshared:96>, <techguns:itemshared:95>, 0.0);
recipes.addShaped(<techguns:itemshared:38>, [[<techguns:itemshared:50>, <techguns:itemshared:55>, null],[<techguns:itemshared:55>, <techguns:itemshared:50>, <techguns:itemshared:55>], [null, <techguns:itemshared:55>, <techguns:itemshared:50>]]);
recipes.addShaped(<techguns:itemshared:19>, [[null, <techguns:itemshared:4>, <techguns:itemshared:4>],[null, <techguns:itemshared:4>, <techguns:itemshared:4>], [null, <techguns:itemshared:4>, <techguns:itemshared:20>]]);
recipes.addShaped(<techguns:itemshared:17>, [[<techguns:itemshared:8>, <techguns:itemshared:8>, <techguns:itemshared:8>],[<techguns:itemshared:8>, <techguns:itemshared:18>, <techguns:itemshared:8>], [<techguns:itemshared:8>, <techguns:itemshared:8>, <techguns:itemshared:8>]]);
recipes.addShaped(<techguns:itemshared:15>, [[<techguns:itemshared:8>, <techguns:itemshared:8>, <techguns:itemshared:8>],[<techguns:itemshared:8>, <techguns:itemshared:8>, <techguns:itemshared:8>], [null, null, <techguns:itemshared:16>]]);
recipes.addShaped(<techguns:itemshared:13>, [[null, <techguns:itemshared:8>, <techguns:itemshared:8>],[null, <techguns:itemshared:8>, <techguns:itemshared:8>], [null, null, <techguns:itemshared:14>]]);
recipes.addShaped(<techguns:itemshared:3> * 8, [[null, null, null],[null, <techguns:itemshared:8>, null], [null, null, null]]);
recipes.addShaped(<techguns:itemshared:8>, [[<techguns:itemshared:3>, <techguns:itemshared:3>, <techguns:itemshared:3>],[<techguns:itemshared:3>, null, <techguns:itemshared:3>], [<techguns:itemshared:3>, <techguns:itemshared:3>, <techguns:itemshared:3>]]);
recipes.addShaped(<techguns:itemshared:14>, [[<techguns:itemshared:55>, <techguns:itemshared:57>, <techguns:itemshared:55>],[<techguns:itemshared:55>, <techguns:itemshared:57>, <techguns:itemshared:55>], [<techguns:itemshared:46>, <techguns:itemshared:55>, <techguns:itemshared:46>]]);
recipes.addShaped(<techguns:itemshared:12>, [[null, <techguns:itemshared:86>, null],[null, <techguns:itemshared:86>, null], [null, <techguns:itemshared:86>, null]]);
recipes.addShaped(<techguns:itemshared:57> * 6, [[null, null, null],[<techguns:itemshared:79>, <minecraft:iron_ingot>, <techguns:itemshared:79>], [null, null, null]]);
recipes.addShaped(<techguns:itemshared:10>, [[<techguns:itemshared:86>, null, <techguns:itemshared:86>],[<techguns:itemshared:86>, <techguns:itemshared:57>, <techguns:itemshared:86>], [<techguns:itemshared:86>, <techguns:itemshared:86>, <techguns:itemshared:86>]]);
recipes.addShaped(<techguns:itemshared:9>, [[<techguns:itemshared:11>, null, null],[<techguns:itemshared:11>, null, null], [<techguns:itemshared:11>, null, <techguns:itemshared:10>]]);
recipes.addShaped(<techguns:itemshared:11>, [[<techguns:itemshared:1>, <techguns:itemshared:1>, <techguns:itemshared:1>],[<techguns:itemshared:1>, <techguns:itemshared:1>, <techguns:itemshared:1>], [<techguns:itemshared:1>, <techguns:itemshared:1>, <techguns:itemshared:12>]]);
recipes.addShaped(<techguns:ladder0:11> * 8, [[<techguns:itemshared:85>, null, <techguns:itemshared:85>],[<techguns:itemshared:64>, <techguns:itemshared:64>, <techguns:itemshared:64>], [<techguns:itemshared:85>, null, <techguns:itemshared:85>]]);
recipes.addShaped(<techguns:ladder0:10> * 8, [[<techguns:ladder0:9>, <techguns:ladder0:9>, <techguns:ladder0:9>],[<techguns:ladder0:9>, <minecraft:potion>, <techguns:ladder0:9>], [<techguns:ladder0:9>, <techguns:ladder0:9>, <techguns:ladder0:9>]]);
recipes.addShaped(<techguns:ladder0:9> * 8, [[<minecraft:iron_ingot>, null, <minecraft:iron_ingot>],[<minecraft:iron_ingot>, <minecraft:iron_ingot>, <minecraft:iron_ingot>], [<minecraft:iron_ingot>, null, <minecraft:iron_ingot>]]);
recipes.addShaped(<techguns:ladder0:8> * 8, [[<techguns:itemshared:82>, null, <techguns:itemshared:82>],[<techguns:itemshared:82>, <techguns:itemshared:82>, <techguns:itemshared:82>], [<techguns:itemshared:82>, null, <techguns:itemshared:82>]]);
recipes.addShaped(<techguns:sandbags>, [[<minecraft:sand>, <minecraft:sand>, <minecraft:sand>],[<minecraft:dirt>, <minecraft:dirt>, <minecraft:dirt>], [<minecraft:sand>, <minecraft:sand>, <minecraft:sand>]]);
furnace.addRecipe(<techguns:itemshared:82>, <techguns:basicore:2>, 0.0);
furnace.addRecipe(<techguns:itemshared:80>, <techguns:basicore:1>, 0.0);
furnace.addRecipe(<techguns:itemshared:79>, <techguns:basicore>, 0.0);
recipes.addShaped(<techguns:basicmachine>, [[<techguns:itemshared:46>, <techguns:itemshared:52>, <techguns:itemshared:46>],[<techguns:itemshared:70>, <techguns:itemshared:50>, <techguns:itemshared:70>], [<techguns:itemshared:47>, <techguns:itemshared:47>, <techguns:itemshared:47>]]);
recipes.addShaped(<techguns:simplemachine:11>, [[<techguns:itemshared:46>, <techguns:itemshared:46>, <techguns:itemshared:46>],[<techguns:itemshared:46>, <minecraft:furnace>, <techguns:itemshared:46>], [<techguns:itemshared:46>, <techguns:itemshared:46>, <techguns:itemshared:46>]]);
recipes.addShaped(<techguns:itemshared:34>, [[null, null, null],[<techguns:itemshared:83>, <techguns:itemshared:57>, <techguns:itemshared:83>], [null, null, <techguns:itemshared:83>]]);
recipes.addShaped(<techguns:itemshared:33>, [[null, null, null],[<minecraft:iron_ingot>, <techguns:itemshared:57>, <minecraft:iron_ingot>], [null, null, <minecraft:iron_ingot>]]);
recipes.addShaped(<techguns:itemshared:62> * 2, [[<techguns:itemshared:86>, <techguns:itemshared:86>, <techguns:itemshared:86>],[<techguns:itemshared:86>, null, <techguns:itemshared:86>], [null, <techguns:itemshared:86>, <techguns:itemshared:86>]]);
recipes.addShaped(<techguns:itemshared:70>, [[<techguns:itemshared:62>, <techguns:itemshared:79>, <techguns:itemshared:62>],[<techguns:itemshared:62>, <techguns:itemshared:79>, <techguns:itemshared:62>], [<techguns:itemshared:62>, <techguns:itemshared:79>, <techguns:itemshared:62>]]);
recipes.addShaped(<techguns:basicmachine:1>, [[<techguns:itemshared:70>, <minecraft:iron_ingot>, <techguns:itemshared:70>],[null, <minecraft:iron_ingot>, null], [<minecraft:iron_ingot>, <minecraft:iron_ingot>, <minecraft:iron_ingot>]]);
recipes.addShaped(<techguns:itemshared:66>, [[null, <techguns:itemshared:64>, null],[null, <techguns:itemshared:65>, null], [null, <techguns:itemshared:64>, null]]);
recipes.addShaped(<techguns:itemshared:65>, [[null, <techguns:itemshared:69>, null],[<techguns:itemshared:62>, <techguns:itemshared:55>, <techguns:itemshared:62>], [null, <techguns:itemshared:69>, null]]);
recipes.addShaped(<techguns:itemshared:88> * 9, [[null, null, null],[null, <techguns:itemshared:83>, null], [null, null, null]]);
recipes.addShaped(<techguns:itemshared:87> * 9, [[null, null, null],[null, <techguns:itemshared:82>, null], [null, null, null]]);
recipes.addShaped(<techguns:itemshared:86> * 9, [[null, null, null],[null, <techguns:itemshared:79>, null], [null, null, null]]);
recipes.addShaped(<minecraft:totem_of_undying>, [[<minecraft:obsidian>, <minecraft:ender_eye>, <minecraft:obsidian>],[<minecraft:obsidian>, <minecraft:magma>, <minecraft:obsidian>], [<minecraft:obsidian>, <minecraft:nether_star>, <minecraft:obsidian>]]);
recipes.addShaped(<minecraft:shield>, [[<minecraft:iron_ingot>, <minecraft:planks>, <minecraft:iron_ingot>],[<minecraft:iron_ingot>, <minecraft:stick>, <minecraft:iron_ingot>], [<minecraft:iron_ingot>, <minecraft:planks>, <minecraft:iron_ingot>]]);
recipes.addShaped(<minecraft:beetroot_soup>, [[<minecraft:slime_ball>, <minecraft:sugar>, <minecraft:slime_ball>],[<minecraft:beetroot>, <minecraft:sugar>, <minecraft:beetroot>], [null, <minecraft:bowl>, null]]);
recipes.addShaped(<minecraft:iron_horse_armor>, [[null, <minecraft:leather>, <minecraft:leather>],[<minecraft:leather>, <minecraft:leather>, <minecraft:iron_ingot>], [<minecraft:iron_ingot>, <minecraft:iron_ingot>, <minecraft:iron_ingot>]]);
recipes.addShaped(<minecraft:golden_horse_armor>, [[null, <minecraft:leather>, <minecraft:leather>],[<minecraft:leather>, <minecraft:leather>, <minecraft:gold_ingot>], [<minecraft:gold_ingot>, <minecraft:gold_ingot>, <minecraft:gold_ingot>]]);
recipes.addShaped(<minecraft:diamond_horse_armor>, [[null, <minecraft:leather>, <minecraft:leather>],[<minecraft:leather>, <minecraft:leather>, <minecraft:diamond>], [<minecraft:diamond>, <minecraft:diamond>, <minecraft:diamond>]]);
recipes.addShaped(<minecraft:name_tag>, [[null, null, <minecraft:leather>],[null, <minecraft:iron_ingot>, null], [<minecraft:iron_ingot>, null, null]]);
recipes.addShaped(<minecraft:lead>, [[<minecraft:leather>, <minecraft:leather>, <minecraft:leather>],[<minecraft:leather>, null, <minecraft:leather>], [<minecraft:string>, <minecraft:leather>, <minecraft:leather>]]);
recipes.addShaped(<minecraft:rabbit_stew>, [[<minecraft:slime_ball>, <minecraft:rabbit>, <minecraft:slime_ball>],[<minecraft:carrot>, <minecraft:potato>, <minecraft:carrot>], [null, <minecraft:bowl>, null]]);
recipes.addShaped(<minecraft:golden_carrot>, [[null, <minecraft:gold_ingot>, null],[<minecraft:gold_ingot>, <minecraft:carrot>, <minecraft:gold_ingot>], [null, <minecraft:gold_ingot>, null]]);
recipes.addShaped(<minecraft:compass>, [[<minecraft:planks>, <minecraft:planks>, <minecraft:planks>],[<minecraft:planks>, <minecraft:iron_ingot>, <minecraft:planks>], [<minecraft:planks>, <minecraft:potion>, <minecraft:planks>]]);
recipes.addShaped(<minecraft:map>, [[null, null, null],[<minecraft:compass>, null, <minecraft:writable_book>], [null, null, null]]);
recipes.addShaped(<minecraft:writable_book>, [[null, null, null],[<minecraft:coal:1>, <minecraft:book>, <minecraft:feather>], [null, null, null]]);
recipes.addShaped(<minecraft:writable_book>, [[null, null, null],[<minecraft:coal>, <minecraft:book>, <minecraft:feather>], [null, null, null]]);
recipes.addShaped(<minecraft:cookie>, [[null, null, null],[<minecraft:bread>, <minecraft:dye:3>, <minecraft:bread>], [null, null, null]]);
recipes.addShaped(<minecraft:cake>, [[<minecraft:milk_bucket>, <minecraft:sugar>, <minecraft:milk_bucket>],[<minecraft:egg>, <minecraft:egg>, <minecraft:egg>], [<minecraft:bread>, <minecraft:bread>, <minecraft:bread>]]);
recipes.addShaped(<minecraft:blaze_rod>, [[null, <minecraft:stick>, <minecraft:blaze_powder>],[<minecraft:stick>, <minecraft:blaze_powder>, <minecraft:stick>], [<minecraft:blaze_powder>, <minecraft:stick>, null]]);
recipes.addShaped(<minecraft:brewing_stand>, [[<minecraft:iron_ingot>, <minecraft:gold_ingot>, <minecraft:iron_ingot>],[null, <minecraft:gold_ingot>, null], [<minecraft:obsidian>, <minecraft:obsidian>, <minecraft:obsidian>]]);
recipes.addShaped(<minecraft:cauldron>, [[null, null, null],[<minecraft:iron_ingot>, <minecraft:potion>, <minecraft:iron_ingot>], [<minecraft:iron_ingot>, <minecraft:iron_ingot>, <minecraft:iron_ingot>]]);
recipes.addShaped(<minecraft:gold_nugget> * 9, [[null, null, null],[null, <minecraft:gold_ingot>, null], [null, null, null]]);
recipes.addShaped(<minecraft:speckled_melon>, [[<minecraft:gold_nugget>, <minecraft:gold_nugget>, <minecraft:gold_nugget>],[<minecraft:gold_nugget>, <minecraft:melon>, <minecraft:gold_nugget>], [<minecraft:gold_nugget>, <minecraft:gold_nugget>, <minecraft:gold_nugget>]]);
recipes.addShaped(<minecraft:magma_cream>, [[null, null, null],[<minecraft:slime_ball>, <minecraft:blaze_powder>, <minecraft:slime_ball>], [null, null, null]]);
furnace.addRecipe(<minecraft:sugar>, <minecraft:reeds>, 0.0);
recipes.addShaped(<minecraft:fermented_spider_eye>, [[null, null, null],[<minecraft:sugar>, <minecraft:spider_eye>, <minecraft:sugar>], [null, null, null]]);
recipes.addShaped(<minecraft:glowstone_dust> * 9, [[null, null, null],[null, <minecraft:glowstone>, null], [null, null, null]]);
recipes.addShaped(<minecraft:clock>, [[<minecraft:iron_ingot>, <minecraft:stick>, <minecraft:iron_ingot>],[<minecraft:iron_ingot>, <techguns:itemshared:70>, <minecraft:planks>], [<minecraft:iron_ingot>, <minecraft:wooden_slab>, <minecraft:iron_ingot>]]);
furnace.addRecipe(<minecraft:leather>, <minecraft:rotten_flesh>, 0.0);
recipes.addShaped(<minecraft:book>, [[<minecraft:leather>, <minecraft:leather>, <minecraft:leather>],[<minecraft:paper>, <minecraft:paper>, <minecraft:paper>], [<minecraft:leather>, <minecraft:leather>, <minecraft:leather>]]);
recipes.addShaped(<minecraft:flint>, [[<minecraft:gravel>, <minecraft:gravel>, null],[<minecraft:gravel>, <minecraft:gravel>, null], [null, null, null]]);
recipes.addShaped(<minecraft:golden_boots>, [[null, null, null],[<minecraft:gold_ingot>, null, <minecraft:gold_ingot>], [<minecraft:gold_ingot>, null, <minecraft:gold_ingot>]]);
recipes.addShaped(<minecraft:golden_leggings>, [[<minecraft:gold_ingot>, <minecraft:gold_ingot>, <minecraft:gold_ingot>],[<minecraft:gold_ingot>, null, <minecraft:gold_ingot>], [<minecraft:gold_ingot>, null, <minecraft:gold_ingot>]]);
recipes.addShaped(<minecraft:golden_chestplate>, [[<minecraft:gold_ingot>, <minecraft:gold_ingot>, <minecraft:gold_ingot>],[<minecraft:gold_ingot>, <minecraft:gold_ingot>, <minecraft:gold_ingot>], [null, <minecraft:gold_ingot>, null]]);
recipes.addShaped(<minecraft:golden_helmet>, [[null, <minecraft:gold_ingot>, null],[<minecraft:gold_ingot>, null, <minecraft:gold_ingot>], [null, null, null]]);
recipes.addShaped(<minecraft:diamond_boots>, [[null, null, null],[<minecraft:diamond>, null, <minecraft:diamond>], [<minecraft:diamond>, null, <minecraft:diamond>]]);
recipes.addShaped(<minecraft:diamond_leggings>, [[<minecraft:diamond>, <minecraft:diamond>, <minecraft:diamond>],[<minecraft:diamond>, null, <minecraft:diamond>], [<minecraft:diamond>, null, <minecraft:diamond>]]);
recipes.addShaped(<minecraft:diamond_chestplate>, [[<minecraft:diamond>, <minecraft:diamond>, <minecraft:diamond>],[<minecraft:diamond>, <minecraft:diamond>, <minecraft:diamond>], [null, <minecraft:diamond>, null]]);
recipes.addShaped(<minecraft:diamond_helmet>, [[null, <minecraft:diamond>, null],[<minecraft:diamond>, null, <minecraft:diamond>], [null, null, null]]);
recipes.addShaped(<minecraft:iron_boots>, [[null, null, null],[<minecraft:iron_ingot>, <minecraft:coal>, <minecraft:iron_ingot>], [<minecraft:iron_ingot>, <minecraft:coal>, <minecraft:iron_ingot>]]);
recipes.addShaped(<minecraft:iron_leggings>, [[<minecraft:iron_ingot>, <minecraft:iron_ingot>, <minecraft:iron_ingot>],[<minecraft:iron_ingot>, <minecraft:coal>, <minecraft:iron_ingot>], [<minecraft:iron_ingot>, <minecraft:coal>, <minecraft:iron_ingot>]]);
recipes.addShaped(<minecraft:iron_chestplate>, [[<minecraft:iron_ingot>, <minecraft:coal>, <minecraft:iron_ingot>],[<minecraft:iron_ingot>, <minecraft:iron_ingot>, <minecraft:iron_ingot>], [<minecraft:coal>, <minecraft:iron_ingot>, <minecraft:coal>]]);
recipes.addShaped(<minecraft:iron_helmet>, [[<minecraft:coal>, <minecraft:iron_ingot>, <minecraft:coal>],[<minecraft:iron_ingot>, null, <minecraft:iron_ingot>], [null, null, null]]);
recipes.addShaped(<minecraft:chainmail_boots>, [[null, null, null],[<minecraft:iron_ingot>, null, <minecraft:iron_ingot>], [<minecraft:iron_ingot>, null, <minecraft:iron_ingot>]]);
recipes.addShaped(<minecraft:chainmail_leggings>, [[<minecraft:iron_ingot>, <minecraft:iron_ingot>, <minecraft:iron_ingot>],[<minecraft:iron_ingot>, null, <minecraft:iron_ingot>], [<minecraft:iron_ingot>, null, <minecraft:iron_ingot>]]);
recipes.addShaped(<minecraft:chainmail_chestplate>, [[<minecraft:iron_ingot>, <minecraft:iron_ingot>, <minecraft:iron_ingot>],[<minecraft:iron_ingot>, <minecraft:iron_ingot>, <minecraft:iron_ingot>], [null, <minecraft:iron_ingot>, null]]);
recipes.addShaped(<minecraft:chainmail_helmet>, [[null, <minecraft:iron_ingot>, null],[<minecraft:iron_ingot>, null, <minecraft:iron_ingot>], [null, null, null]]);
furnace.addRecipe(<minecraft:bread>, <minecraft:wheat>, 0.0);
recipes.addShaped(<minecraft:golden_hoe>, [[<minecraft:gold_ingot>, <minecraft:gold_ingot>, null],[null, <minecraft:stick>, null], [null, <minecraft:stick>, null]]);
recipes.addShaped(<minecraft:diamond_hoe>, [[<minecraft:diamond>, <minecraft:diamond>, null],[null, <minecraft:stick>, null], [null, <minecraft:stick>, null]]);
recipes.addShaped(<minecraft:iron_hoe>, [[<minecraft:iron_ingot>, <minecraft:iron_ingot>, null],[null, <minecraft:stick>, null], [null, <minecraft:stick>, null]]);
recipes.addShaped(<minecraft:stone_hoe>, [[<minecraft:cobblestone>, <minecraft:cobblestone>, null],[null, <minecraft:stick>, null], [null, <minecraft:stick>, null]]);
recipes.addShaped(<minecraft:wooden_hoe>, [[<minecraft:planks>, <minecraft:planks>, null],[null, <minecraft:stick>, null], [null, <minecraft:stick>, null]]);
recipes.addShaped(<minecraft:tnt>, [[<minecraft:paper>, <minecraft:gunpowder>, <minecraft:paper>],[<minecraft:paper>, <minecraft:sand>, <minecraft:paper>], [<minecraft:paper>, <minecraft:gunpowder>, <minecraft:paper>]]);
recipes.addShaped(<minecraft:gunpowder>, [[<minecraft:sand:1>, <minecraft:sand:1>, <minecraft:sand:1>],[<minecraft:sand:1>, <minecraft:magma>, <minecraft:sand:1>], [<minecraft:sand:1>, <minecraft:coal:1>, <minecraft:sand:1>]]);
recipes.addShaped(<minecraft:golden_axe>, [[<minecraft:gold_ingot>, <minecraft:gold_ingot>, null],[<minecraft:gold_ingot>, <minecraft:stick>, null], [null, <minecraft:stick>, null]]);
recipes.addShaped(<minecraft:golden_pickaxe>, [[<minecraft:gold_ingot>, <minecraft:gold_ingot>, <minecraft:gold_ingot>],[null, <minecraft:stick>, null], [null, <minecraft:stick>, null]]);
recipes.addShaped(<minecraft:golden_shovel>, [[null, <minecraft:gold_ingot>, null],[null, <minecraft:stick>, null], [null, <minecraft:stick>, null]]);
recipes.addShaped(<minecraft:golden_sword>, [[null, null, <minecraft:gold_ingot>],[null, <minecraft:gold_ingot>, null], [<minecraft:stick>, null, null]]);
recipes.addShaped(<minecraft:mushroom_stew>, [[<minecraft:red_mushroom>, <minecraft:slime_ball>, <minecraft:brown_mushroom>],[<minecraft:slime_ball>, <minecraft:brown_mushroom>, <minecraft:slime_ball>], [null, <minecraft:bowl>, null]]);
recipes.addShaped(<minecraft:mushroom_stew>, [[<minecraft:brown_mushroom>, <minecraft:slime_ball>, <minecraft:brown_mushroom>],[<minecraft:slime_ball>, <minecraft:red_mushroom>, <minecraft:slime_ball>], [null, <minecraft:bowl>, null]]);
recipes.addShaped(<minecraft:mushroom_stew>, [[<minecraft:brown_mushroom>, <minecraft:slime_ball>, <minecraft:red_mushroom>],[<minecraft:slime_ball>, <minecraft:brown_mushroom>, <minecraft:slime_ball>], [null, <minecraft:bowl>, null]]);
recipes.addShaped(<minecraft:mushroom_stew>, [[<minecraft:red_mushroom>, <minecraft:slime_ball>, <minecraft:brown_mushroom>],[<minecraft:slime_ball>, <minecraft:red_mushroom>, <minecraft:slime_ball>], [null, <minecraft:bowl>, null]]);
recipes.addShaped(<minecraft:mushroom_stew>, [[<minecraft:red_mushroom>, <minecraft:slime_ball>, <minecraft:red_mushroom>],[<minecraft:slime_ball>, <minecraft:brown_mushroom>, <minecraft:slime_ball>], [null, <minecraft:bowl>, null]]);
recipes.addShaped(<minecraft:mushroom_stew>, [[<minecraft:brown_mushroom>, <minecraft:slime_ball>, <minecraft:red_mushroom>],[<minecraft:slime_ball>, <minecraft:red_mushroom>, <minecraft:slime_ball>], [null, <minecraft:bowl>, null]]);
recipes.addShaped(<minecraft:mushroom_stew>, [[<minecraft:red_mushroom>, <minecraft:slime_ball>, <minecraft:red_mushroom>],[<minecraft:slime_ball>, <minecraft:red_mushroom>, <minecraft:slime_ball>], [null, <minecraft:bowl>, null]]);
recipes.addShaped(<minecraft:mushroom_stew>, [[<minecraft:brown_mushroom>, <minecraft:slime_ball>, <minecraft:brown_mushroom>],[<minecraft:slime_ball>, <minecraft:brown_mushroom>, <minecraft:slime_ball>], [null, <minecraft:bowl>, null]]);
recipes.addShaped(<minecraft:slime_ball> * 9, [[null, null, null],[null, <minecraft:slime>, null], [null, null, null]]);
recipes.addShaped(<minecraft:bowl> * 4, [[null, null, null],[<minecraft:planks>, null, <minecraft:planks>], [<minecraft:planks>, <minecraft:planks>, <minecraft:planks>]]);
recipes.addShaped(<minecraft:diamond_axe>, [[<minecraft:diamond>, <minecraft:diamond>, null],[<minecraft:diamond>, <minecraft:stick>, null], [null, <minecraft:stick>, null]]);
recipes.addShaped(<minecraft:diamond_pickaxe>, [[<minecraft:diamond>, <minecraft:diamond>, <minecraft:diamond>],[null, <minecraft:stick>, null], [null, <minecraft:stick>, null]]);
recipes.addShaped(<minecraft:diamond_shovel>, [[null, <minecraft:diamond>, null],[null, <minecraft:stick>, null], [null, <minecraft:stick>, null]]);
recipes.addShaped(<minecraft:diamond_sword>, [[null, null, <minecraft:diamond>],[null, <minecraft:diamond>, null], [<minecraft:stick>, null, null]]);
recipes.addShaped(<minecraft:stone_axe>, [[<minecraft:cobblestone>, <minecraft:cobblestone>, null],[<minecraft:cobblestone>, <minecraft:stick>, null], [null, <minecraft:stick>, null]]);
recipes.addShaped(<minecraft:stone_pickaxe>, [[<minecraft:cobblestone>, <minecraft:cobblestone>, <minecraft:cobblestone>],[null, <minecraft:stick>, null], [null, <minecraft:stick>, null]]);
recipes.addShaped(<minecraft:stone_shovel>, [[null, <minecraft:cobblestone>, null],[null, <minecraft:stick>, null], [null, <minecraft:stick>, null]]);
recipes.addShaped(<minecraft:stone_sword>, [[null, null, <minecraft:cobblestone>],[null, <minecraft:cobblestone>, null], [<minecraft:stick>, null, null]]);
recipes.addShaped(<minecraft:wooden_axe>, [[<minecraft:planks>, <minecraft:planks>, null],[<minecraft:planks>, <minecraft:stick>, null], [null, <minecraft:stick>, null]]);
recipes.addShaped(<minecraft:wooden_pickaxe>, [[<minecraft:planks>, <minecraft:planks>, <minecraft:planks>],[null, <minecraft:stick>, null], [null, <minecraft:stick>, null]]);
recipes.addShaped(<minecraft:wooden_shovel>, [[null, <minecraft:planks>, null],[null, <minecraft:stick>, null], [null, <minecraft:stick>, null]]);
recipes.addShaped(<minecraft:wooden_sword>, [[null, null, <minecraft:planks>],[null, <minecraft:planks>, null], [<minecraft:stick>, null, null]]);
recipes.addShaped(<minecraft:iron_sword>, [[null, null, <minecraft:iron_ingot>],[null, <minecraft:iron_ingot>, null], [<minecraft:stick>, null, null]]);
recipes.addShaped(<minecraft:arrow> * 3, [[null, null, <minecraft:cobblestone>],[null, <minecraft:stick>, null], [<minecraft:stick>, null, null]]);
recipes.addShaped(<minecraft:bow>, [[<minecraft:planks>, <minecraft:stick>, <minecraft:stick>],[<minecraft:stick>, null, <minecraft:string>], [<minecraft:stick>, <minecraft:string>, <minecraft:string>]]);
recipes.addShaped(<minecraft:flint_and_steel>, [[null, null, null],[<minecraft:iron_ingot>, <minecraft:paper>, <minecraft:flint>], [null, null, null]]);
recipes.addShaped(<minecraft:iron_axe>, [[<minecraft:iron_ingot>, <minecraft:iron_ingot>, null],[<minecraft:iron_ingot>, <minecraft:stick>, null], [null, <minecraft:stick>, null]]);
recipes.addShaped(<minecraft:iron_pickaxe>, [[<minecraft:iron_ingot>, <minecraft:iron_ingot>, <minecraft:iron_ingot>],[null, <minecraft:stick>, null], [null, <minecraft:stick>, null]]);
recipes.addShaped(<minecraft:iron_shovel>, [[null, <minecraft:iron_ingot>, null],[null, <minecraft:stick>, null], [null, <minecraft:stick>, null]]);
recipes.addShaped(<minecraft:minecart>, [[<minecraft:iron_ingot>, null, <minecraft:iron_ingot>],[<minecraft:iron_ingot>, <minecraft:iron_ingot>, <minecraft:iron_ingot>], [<minecraft:redstone>, <minecraft:redstone>, <minecraft:redstone>]]);
recipes.addShaped(<minecraft:iron_door>, [[<minecraft:iron_ingot>, <minecraft:iron_ingot>, null],[<minecraft:stick>, <minecraft:iron_ingot>, null], [<minecraft:iron_ingot>, <minecraft:iron_ingot>, null]]);
recipes.addShaped(<minecraft:dark_oak_door>, [[<minecraft:planks:5>, <minecraft:planks:5>, null],[<minecraft:stick>, <minecraft:planks:5>, null], [<minecraft:planks:5>, <minecraft:planks:5>, null]]);
recipes.addShaped(<minecraft:acacia_door>, [[<minecraft:planks:4>, <minecraft:planks:4>, null],[<minecraft:stick>, <minecraft:planks:4>, null], [<minecraft:planks:4>, <minecraft:planks:4>, null]]);
recipes.addShaped(<minecraft:jungle_door>, [[<minecraft:planks:3>, <minecraft:planks:3>, null],[<minecraft:stick>, <minecraft:planks:3>, null], [<minecraft:planks:3>, <minecraft:planks:3>, null]]);
recipes.addShaped(<minecraft:birch_door>, [[<minecraft:planks:2>, <minecraft:planks:2>, null],[<minecraft:stick>, <minecraft:planks:2>, null], [<minecraft:planks:2>, <minecraft:planks:2>, null]]);
recipes.addShaped(<minecraft:spruce_door>, [[<minecraft:planks:1>, <minecraft:planks:1>, null],[<minecraft:stick>, <minecraft:planks:1>, null], [<minecraft:planks:1>, <minecraft:planks:1>, null]]);
recipes.addShaped(<minecraft:wooden_door>, [[<minecraft:planks>, <minecraft:planks>, null],[<minecraft:stick>, <minecraft:planks>, null], [<minecraft:planks>, <minecraft:planks>, null]]);
recipes.addShaped(<minecraft:dark_oak_fence_gate>, [[<minecraft:stick>, null, <minecraft:stick>],[<minecraft:stick>, <minecraft:planks:5>, <minecraft:stick>], [<minecraft:stick>, null, <minecraft:stick>]]);
recipes.addShaped(<minecraft:acacia_fence_gate>, [[<minecraft:stick>, null, <minecraft:stick>],[<minecraft:stick>, <minecraft:planks:4>, <minecraft:stick>], [<minecraft:stick>, null, <minecraft:stick>]]);
recipes.addShaped(<minecraft:jungle_fence_gate>, [[<minecraft:stick>, null, <minecraft:stick>],[<minecraft:stick>, <minecraft:planks:3>, <minecraft:stick>], [<minecraft:stick>, null, <minecraft:stick>]]);
recipes.addShaped(<minecraft:birch_fence_gate>, [[<minecraft:stick>, null, <minecraft:stick>],[<minecraft:stick>, <minecraft:planks:2>, <minecraft:stick>], [<minecraft:stick>, null, <minecraft:stick>]]);
recipes.addShaped(<minecraft:spruce_fence_gate>, [[<minecraft:stick>, null, <minecraft:stick>],[<minecraft:stick>, <minecraft:planks:1>, <minecraft:stick>], [<minecraft:stick>, null, <minecraft:stick>]]);
recipes.addShaped(<minecraft:iron_trapdoor>, [[<minecraft:iron_ingot>, <minecraft:stick>, <minecraft:iron_ingot>],[<minecraft:stick>, <minecraft:iron_ingot>, <minecraft:stick>], [<minecraft:iron_ingot>, <minecraft:stick>, <minecraft:iron_ingot>]]);
recipes.addShaped(<minecraft:redstone_block>, [[<minecraft:redstone>, <minecraft:redstone>, <minecraft:redstone>],[<minecraft:redstone>, <minecraft:redstone>, <minecraft:redstone>], [<minecraft:redstone>, <minecraft:redstone>, <minecraft:redstone>]]);
recipes.addShaped(<minecraft:redstone> * 9, [[null, null, null],[null, <minecraft:redstone_block>, null], [null, null, null]]);
recipes.addShaped(<minecraft:tripwire_hook>, [[null, <minecraft:cobblestone>, null],[null, <minecraft:planks>, null], [<minecraft:redstone>, <minecraft:redstone>, <minecraft:redstone>]]);
recipes.addShaped(<minecraft:wooden_button>, [[null, null, null],[<minecraft:redstone>, <minecraft:planks>, <minecraft:redstone>], [null, null, null]]);
recipes.addShaped(<minecraft:stone_button>, [[null, null, null],[<minecraft:redstone>, <minecraft:cobblestone>, <minecraft:redstone>], [null, null, null]]);
recipes.addShaped(<minecraft:wooden_pressure_plate>, [[null, null, null],[<minecraft:planks>, <minecraft:redstone>, <minecraft:planks>], [<minecraft:redstone>, <minecraft:redstone>, <minecraft:redstone>]]);
recipes.addShaped(<minecraft:stone_pressure_plate>, [[null, null, null],[<minecraft:cobblestone>, <minecraft:redstone>, <minecraft:cobblestone>], [<minecraft:redstone>, <minecraft:redstone>, <minecraft:redstone>]]);
recipes.addShaped(<minecraft:redstone_lamp>, [[<minecraft:redstone>, null, <minecraft:redstone>],[null, <minecraft:sea_lantern>, null], [<minecraft:redstone>, null, <minecraft:redstone>]]);
recipes.addShaped(<minecraft:fence_gate>, [[<minecraft:stick>, null, <minecraft:stick>],[<minecraft:stick>, <minecraft:planks>, <minecraft:stick>], [<minecraft:stick>, null, <minecraft:stick>]]);
recipes.addShaped(<minecraft:trapdoor>, [[<minecraft:planks>, <minecraft:stick>, <minecraft:planks>],[<minecraft:stick>, <minecraft:planks>, <minecraft:stick>], [<minecraft:planks>, <minecraft:stick>, <minecraft:planks>]]);
recipes.addShaped(<minecraft:redstone_torch>, [[null, null, null],[null, <minecraft:redstone>, null], [null, <minecraft:torch>, null]]);
furnace.addRecipe(<minecraft:coal:1>, <minecraft:log>, 0.0);
recipes.addShaped(<minecraft:banner>, [[<minecraft:wool:15>, <minecraft:stick>, <minecraft:wool:15>],[<minecraft:wool:15>, <minecraft:stick>, <minecraft:wool:15>], [null, <minecraft:stick>, null]]);
recipes.addShaped(<minecraft:banner:1>, [[<minecraft:wool:14>, <minecraft:stick>, <minecraft:wool:14>],[<minecraft:wool:14>, <minecraft:stick>, <minecraft:wool:14>], [null, <minecraft:stick>, null]]);
recipes.addShaped(<minecraft:banner:2>, [[<minecraft:wool:13>, <minecraft:stick>, <minecraft:wool:13>],[<minecraft:wool:13>, <minecraft:stick>, <minecraft:wool:13>], [null, <minecraft:stick>, null]]);
recipes.addShaped(<minecraft:banner:3>, [[<minecraft:wool:12>, <minecraft:stick>, <minecraft:wool:12>],[<minecraft:wool:12>, <minecraft:stick>, <minecraft:wool:12>], [null, <minecraft:stick>, null]]);
recipes.addShaped(<minecraft:banner:4>, [[<minecraft:wool:11>, <minecraft:stick>, <minecraft:wool:11>],[<minecraft:wool:11>, <minecraft:stick>, <minecraft:wool:11>], [null, <minecraft:stick>, null]]);
recipes.addShaped(<minecraft:banner:5>, [[<minecraft:wool:10>, <minecraft:stick>, <minecraft:wool:10>],[<minecraft:wool:10>, <minecraft:stick>, <minecraft:wool:10>], [null, <minecraft:stick>, null]]);
recipes.addShaped(<minecraft:banner:6>, [[<minecraft:wool:9>, <minecraft:stick>, <minecraft:wool:9>],[<minecraft:wool:9>, <minecraft:stick>, <minecraft:wool:9>], [null, <minecraft:stick>, null]]);
recipes.addShaped(<minecraft:banner:7>, [[<minecraft:wool:8>, <minecraft:stick>, <minecraft:wool:8>],[<minecraft:wool:8>, <minecraft:stick>, <minecraft:wool:8>], [null, <minecraft:stick>, null]]);
recipes.addShaped(<minecraft:banner:8>, [[<minecraft:wool:7>, <minecraft:stick>, <minecraft:wool:7>],[<minecraft:wool:7>, <minecraft:stick>, <minecraft:wool:7>], [null, <minecraft:stick>, null]]);
recipes.addShaped(<minecraft:banner:9>, [[<minecraft:wool:6>, <minecraft:stick>, <minecraft:wool:6>],[<minecraft:wool:6>, <minecraft:stick>, <minecraft:wool:6>], [null, <minecraft:stick>, null]]);
recipes.addShaped(<minecraft:banner:10>, [[<minecraft:wool:5>, <minecraft:stick>, <minecraft:wool:5>],[<minecraft:wool:5>, <minecraft:stick>, <minecraft:wool:5>], [null, <minecraft:stick>, null]]);
recipes.addShaped(<minecraft:banner:11>, [[<minecraft:wool:4>, <minecraft:stick>, <minecraft:wool:4>],[<minecraft:wool:4>, <minecraft:stick>, <minecraft:wool:4>], [null, <minecraft:stick>, null]]);
recipes.addShaped(<minecraft:banner:12>, [[<minecraft:wool:3>, <minecraft:stick>, <minecraft:wool:3>],[<minecraft:wool:3>, <minecraft:stick>, <minecraft:wool:3>], [null, <minecraft:stick>, null]]);
recipes.addShaped(<minecraft:banner:13>, [[<minecraft:wool:2>, <minecraft:stick>, <minecraft:wool:2>],[<minecraft:wool:2>, <minecraft:stick>, <minecraft:wool:2>], [null, <minecraft:stick>, null]]);
recipes.addShaped(<minecraft:banner:14>, [[<minecraft:wool:1>, <minecraft:stick>, <minecraft:wool:1>],[<minecraft:wool:1>, <minecraft:stick>, <minecraft:wool:1>], [null, <minecraft:stick>, null]]);
recipes.addShaped(<minecraft:banner:15>, [[<minecraft:wool>, <minecraft:stick>, <minecraft:wool>],[<minecraft:wool>, <minecraft:stick>, <minecraft:wool>], [null, <minecraft:stick>, null]]);
recipes.addShaped(<minecraft:armor_stand>, [[<minecraft:planks>, <minecraft:planks>, <minecraft:planks>],[null, <minecraft:planks>, null], [<minecraft:stone>, <minecraft:stone>, <minecraft:stone>]]);
recipes.addShaped(<minecraft:flower_pot>, [[null, null, null],[<techguns:itemshared:55>, null, <techguns:itemshared:55>], [null, <techguns:itemshared:55>, null]]);
recipes.addShaped(<minecraft:item_frame>, [[null, <minecraft:stick>, null],[<minecraft:planks>, <minecraft:stick>, <minecraft:planks>], [<minecraft:planks>, <minecraft:planks>, <minecraft:planks>]]);
recipes.addShaped(<minecraft:bed:15>, [[null, null, null],[<minecraft:wool:15>, <minecraft:wool:15>, <minecraft:wool:15>], [<minecraft:planks>, <minecraft:planks>, <minecraft:planks>]]);
recipes.addShaped(<minecraft:bed:14>, [[null, null, null],[<minecraft:wool:14>, <minecraft:wool:14>, <minecraft:wool:14>], [<minecraft:planks>, <minecraft:planks>, <minecraft:planks>]]);
recipes.addShaped(<minecraft:bed:13>, [[null, null, null],[<minecraft:wool:13>, <minecraft:wool:13>, <minecraft:wool:13>], [<minecraft:planks>, <minecraft:planks>, <minecraft:planks>]]);
recipes.addShaped(<minecraft:bed:12>, [[null, null, null],[<minecraft:wool:12>, <minecraft:wool:12>, <minecraft:wool:12>], [<minecraft:planks>, <minecraft:planks>, <minecraft:planks>]]);
recipes.addShaped(<minecraft:bed:11>, [[null, null, null],[<minecraft:wool:11>, <minecraft:wool:11>, <minecraft:wool:11>], [<minecraft:planks>, <minecraft:planks>, <minecraft:planks>]]);
recipes.addShaped(<minecraft:bed:10>, [[null, null, null],[<minecraft:wool:10>, <minecraft:wool:10>, <minecraft:wool:10>], [<minecraft:planks>, <minecraft:planks>, <minecraft:planks>]]);
recipes.addShaped(<minecraft:bed:9>, [[null, null, null],[<minecraft:wool:9>, <minecraft:wool:9>, <minecraft:wool:9>], [<minecraft:planks>, <minecraft:planks>, <minecraft:planks>]]);
recipes.addShaped(<minecraft:bed:8>, [[null, null, null],[<minecraft:wool:8>, <minecraft:wool:8>, <minecraft:wool:8>], [<minecraft:planks>, <minecraft:planks>, <minecraft:planks>]]);
recipes.addShaped(<minecraft:bed:7>, [[null, null, null],[<minecraft:wool:7>, <minecraft:wool:7>, <minecraft:wool:7>], [<minecraft:planks>, <minecraft:planks>, <minecraft:planks>]]);
recipes.addShaped(<minecraft:bed:6>, [[null, null, null],[<minecraft:wool:6>, <minecraft:wool:6>, <minecraft:wool:6>], [<minecraft:planks>, <minecraft:planks>, <minecraft:planks>]]);
recipes.addShaped(<minecraft:bed:5>, [[null, null, null],[<minecraft:wool:5>, <minecraft:wool:5>, <minecraft:wool:5>], [<minecraft:planks>, <minecraft:planks>, <minecraft:planks>]]);
recipes.addShaped(<minecraft:bed:4>, [[null, null, null],[<minecraft:wool:4>, <minecraft:wool:4>, <minecraft:wool:4>], [<minecraft:planks>, <minecraft:planks>, <minecraft:planks>]]);
recipes.addShaped(<minecraft:bed:3>, [[null, null, null],[<minecraft:wool:3>, <minecraft:wool:3>, <minecraft:wool:3>], [<minecraft:planks>, <minecraft:planks>, <minecraft:planks>]]);
recipes.addShaped(<minecraft:bed:2>, [[null, null, null],[<minecraft:wool:2>, <minecraft:wool:2>, <minecraft:wool:2>], [<minecraft:planks>, <minecraft:planks>, <minecraft:planks>]]);
recipes.addShaped(<minecraft:bed:1>, [[null, null, null],[<minecraft:wool:1>, <minecraft:wool:1>, <minecraft:wool:1>], [<minecraft:planks>, <minecraft:planks>, <minecraft:planks>]]);
recipes.addShaped(<minecraft:bed>, [[null, null, null],[<minecraft:wool>, <minecraft:wool>, <minecraft:wool>], [<minecraft:planks>, <minecraft:planks>, <minecraft:planks>]]);
recipes.addShaped(<minecraft:sign>, [[null, null, null],[<minecraft:stick>, <minecraft:planks>, <minecraft:stick>], [<minecraft:stick>, null, <minecraft:stick>]]);
recipes.addShaped(<minecraft:end_rod>, [[null, null, null],[null, <minecraft:chorus_fruit>, null], [null, <minecraft:torch>, null]]);
recipes.addShaped(<minecraft:dark_oak_fence> * 8, [[null, null, null],[<minecraft:planks:5>, <minecraft:stick>, <minecraft:planks:5>], [<minecraft:planks:5>, null, <minecraft:planks:5>]]);
recipes.addShaped(<minecraft:acacia_fence> * 8, [[null, null, null],[<minecraft:planks:4>, <minecraft:stick>, <minecraft:planks:4>], [<minecraft:planks:4>, null, <minecraft:planks:4>]]);
recipes.addShaped(<minecraft:jungle_fence> * 8, [[null, null, null],[<minecraft:planks:3>, <minecraft:stick>, <minecraft:planks:3>], [<minecraft:planks:3>, null, <minecraft:planks:3>]]);
recipes.addShaped(<minecraft:birch_fence> * 8, [[null, null, null],[<minecraft:planks:2>, <minecraft:stick>, <minecraft:planks:2>], [<minecraft:planks:2>, null, <minecraft:planks:2>]]);
recipes.addShaped(<minecraft:spruce_fence> * 8, [[null, null, null],[<minecraft:planks:1>, <minecraft:stick>, <minecraft:planks:1>], [<minecraft:planks:1>, null, <minecraft:planks:1>]]);
recipes.addShaped(<minecraft:slime> * 4, [[<minecraft:rotten_flesh>, <minecraft:magma>, <minecraft:rotten_flesh>],[<minecraft:magma>, <minecraft:potion>, <minecraft:magma>], [<minecraft:rotten_flesh>, <minecraft:magma>, <minecraft:rotten_flesh>]]);
recipes.addShaped(<minecraft:stained_glass_pane:15> * 8, [[<minecraft:stained_glass:15>, <minecraft:stained_glass:15>, null],[<minecraft:stained_glass:15>, <minecraft:stained_glass:15>, null], [null, null, null]]);
recipes.addShaped(<minecraft:stained_glass_pane:14> * 8, [[<minecraft:stained_glass:14>, <minecraft:stained_glass:14>, null],[<minecraft:stained_glass:14>, <minecraft:stained_glass:14>, null], [null, null, null]]);
recipes.addShaped(<minecraft:stained_glass_pane:13> * 8, [[<minecraft:stained_glass:13>, <minecraft:stained_glass:13>, null],[<minecraft:stained_glass:13>, <minecraft:stained_glass:13>, null], [null, null, null]]);
recipes.addShaped(<minecraft:stained_glass_pane:12> * 8, [[<minecraft:stained_glass:12>, <minecraft:stained_glass:12>, null],[<minecraft:stained_glass:12>, <minecraft:stained_glass:12>, null], [null, null, null]]);
recipes.addShaped(<minecraft:stained_glass_pane:11> * 8, [[<minecraft:stained_glass:11>, <minecraft:stained_glass:11>, null],[<minecraft:stained_glass:11>, <minecraft:stained_glass:11>, null], [null, null, null]]);
recipes.addShaped(<minecraft:stained_glass_pane:10> * 8, [[<minecraft:stained_glass:10>, <minecraft:stained_glass:10>, null],[<minecraft:stained_glass:10>, <minecraft:stained_glass:10>, null], [null, null, null]]);
recipes.addShaped(<minecraft:stained_glass_pane:9> * 8, [[<minecraft:stained_glass:9>, <minecraft:stained_glass:9>, null],[<minecraft:stained_glass:9>, <minecraft:stained_glass:9>, null], [null, null, null]]);
recipes.addShaped(<minecraft:stained_glass_pane:8> * 8, [[<minecraft:stained_glass:8>, <minecraft:stained_glass:8>, null],[<minecraft:stained_glass:8>, <minecraft:stained_glass:8>, null], [null, null, null]]);
recipes.addShaped(<minecraft:stained_glass_pane:7> * 8, [[<minecraft:stained_glass:7>, <minecraft:stained_glass:7>, null],[<minecraft:stained_glass:7>, <minecraft:stained_glass:7>, null], [null, null, null]]);
recipes.addShaped(<minecraft:stained_glass_pane:6> * 8, [[<minecraft:stained_glass:6>, <minecraft:stained_glass:6>, null],[<minecraft:stained_glass:6>, <minecraft:stained_glass:6>, null], [null, null, null]]);
recipes.addShaped(<minecraft:stained_glass_pane:5> * 8, [[<minecraft:stained_glass:5>, <minecraft:stained_glass:5>, null],[<minecraft:stained_glass:5>, <minecraft:stained_glass:5>, null], [null, null, null]]);
recipes.addShaped(<minecraft:stained_glass_pane:4> * 8, [[<minecraft:stained_glass:4>, <minecraft:stained_glass:4>, null],[<minecraft:stained_glass:4>, <minecraft:stained_glass:4>, null], [null, null, null]]);
recipes.addShaped(<minecraft:stained_glass_pane:3> * 8, [[<minecraft:stained_glass:3>, <minecraft:stained_glass:3>, null],[<minecraft:stained_glass:3>, <minecraft:stained_glass:3>, null], [null, null, null]]);
recipes.addShaped(<minecraft:stained_glass_pane:2> * 8, [[<minecraft:stained_glass:2>, <minecraft:stained_glass:2>, null],[<minecraft:stained_glass:2>, <minecraft:stained_glass:2>, null], [null, null, null]]);
recipes.addShaped(<minecraft:stained_glass_pane:1> * 8, [[<minecraft:stained_glass:1>, <minecraft:stained_glass:1>, null],[<minecraft:stained_glass:1>, <minecraft:stained_glass:1>, null], [null, null, null]]);
recipes.addShaped(<minecraft:stained_glass_pane> * 8, [[<minecraft:stained_glass>, <minecraft:stained_glass>, null],[<minecraft:stained_glass>, <minecraft:stained_glass>, null], [null, null, null]]);
recipes.addShaped(<minecraft:nether_brick_fence> * 8, [[null, null, null],[<minecraft:nether_brick>, null, <minecraft:nether_brick>], [<minecraft:nether_brick>, <minecraft:nether_brick>, <minecraft:nether_brick>]]);
recipes.addShaped(<minecraft:anvil>, [[<minecraft:iron_block>, <minecraft:iron_block>, <minecraft:iron_block>],[<minecraft:stone>, <minecraft:chest>, <minecraft:stone>], [<minecraft:stone>, <minecraft:stone>, <minecraft:stone>]]);
recipes.addShaped(<minecraft:mossy_cobblestone> * 8, [[<minecraft:cobblestone>, <minecraft:cobblestone>, <minecraft:cobblestone>],[<minecraft:cobblestone>, <minecraft:potion>, <minecraft:cobblestone>], [<minecraft:cobblestone>, <minecraft:cobblestone>, <minecraft:cobblestone>]]);
recipes.addShaped(<minecraft:cobblestone_wall:1> * 8, [[<minecraft:cobblestone_wall>, <minecraft:cobblestone_wall>, <minecraft:cobblestone_wall>],[<minecraft:cobblestone_wall>, <minecraft:potion>, <minecraft:cobblestone_wall>], [<minecraft:cobblestone_wall>, <minecraft:cobblestone_wall>, <minecraft:cobblestone_wall>]]);
recipes.addShaped(<minecraft:cobblestone_wall> * 8, [[null, null, null],[<minecraft:cobblestone>, null, <minecraft:cobblestone>], [<minecraft:cobblestone>, <minecraft:cobblestone>, <minecraft:cobblestone>]]);
recipes.addShaped(<minecraft:fence> * 8, [[null, null, null],[<minecraft:planks>, <minecraft:stick>, <minecraft:planks>], [<minecraft:planks>, null, <minecraft:planks>]]);
recipes.addShaped(<minecraft:ladder> * 12, [[<minecraft:planks>, null, <minecraft:planks>],[<minecraft:planks>, <minecraft:stick>, <minecraft:planks>], [<minecraft:planks>, null, <minecraft:planks>]]);
recipes.addShaped(<minecraft:furnace>, [[null, <minecraft:cobblestone>, null],[<minecraft:cobblestone>, <minecraft:log>, <minecraft:cobblestone>], [<minecraft:cobblestone>, <minecraft:cobblestone>, <minecraft:cobblestone>]]);
recipes.addShaped(<minecraft:crafting_table>, [[<minecraft:stick>, <minecraft:iron_ingot>, <minecraft:stick>],[<minecraft:planks>, <minecraft:log>, <minecraft:planks>], [<minecraft:planks>, <minecraft:planks>, <minecraft:planks>]]);
recipes.addShaped(<minecraft:chest>, [[null, <minecraft:planks>, null],[<minecraft:planks>, null, <minecraft:planks>], [null, <minecraft:planks>, null]]);
recipes.addShaped(<minecraft:stick> * 9, [[null, <minecraft:planks>, null],[null, <minecraft:planks>, null], [null, <minecraft:planks>, null]]);
recipes.addShaped(<minecraft:torch> * 8, [[null, <minecraft:coal>, null],[null, <minecraft:stick>, null], [null, <minecraft:stick>, null]]);
furnace.addRecipe(<minecraft:concrete:15>, <minecraft:concrete_powder:15>, 0.0);
furnace.addRecipe(<minecraft:concrete:14>, <minecraft:concrete_powder:14>, 0.0);
furnace.addRecipe(<minecraft:concrete:13>, <minecraft:concrete_powder:13>, 0.0);
furnace.addRecipe(<minecraft:concrete:12>, <minecraft:concrete_powder:12>, 0.0);
furnace.addRecipe(<minecraft:concrete:11>, <minecraft:concrete_powder:11>, 0.0);
furnace.addRecipe(<minecraft:concrete:10>, <minecraft:concrete_powder:10>, 0.0);
furnace.addRecipe(<minecraft:concrete:9>, <minecraft:concrete_powder:9>, 0.0);
furnace.addRecipe(<minecraft:concrete:8>, <minecraft:concrete_powder:8>, 0.0);
furnace.addRecipe(<minecraft:concrete:7>, <minecraft:concrete_powder:7>, 0.0);
furnace.addRecipe(<minecraft:concrete:6>, <minecraft:concrete_powder:6>, 0.0);
furnace.addRecipe(<minecraft:concrete:5>, <minecraft:concrete_powder:5>, 0.0);
furnace.addRecipe(<minecraft:concrete:4>, <minecraft:concrete_powder:4>, 0.0);
furnace.addRecipe(<minecraft:concrete:3>, <minecraft:concrete_powder:3>, 0.0);
furnace.addRecipe(<minecraft:concrete:2>, <minecraft:concrete_powder:2>, 0.0);
furnace.addRecipe(<minecraft:concrete:1>, <minecraft:concrete_powder:1>, 0.0);
furnace.addRecipe(<minecraft:concrete>, <minecraft:concrete_powder>, 0.0);
recipes.addShaped(<minecraft:dye:15> * 10, [[<minecraft:bone_block>, <minecraft:dirt:2>, <minecraft:bone_block>],[<minecraft:sand>, <minecraft:bone_block>, <minecraft:sand>], [<minecraft:bone_block>, <minecraft:dirt:2>, <minecraft:bone_block>]]);
recipes.addShaped(<minecraft:bone_block>, [[<minecraft:bone>, <minecraft:bone>, <minecraft:bone>],[<minecraft:bone>, <minecraft:bone>, <minecraft:bone>], [<minecraft:bone>, <minecraft:bone>, <minecraft:bone>]]);
recipes.addShaped(<minecraft:bone> * 9, [[null, null, null],[null, <minecraft:bone_block>, null], [null, null, null]]);
recipes.addShaped(<minecraft:red_nether_brick> * 5, [[<minecraft:nether_brick>, <minecraft:glass>, <minecraft:nether_brick>],[<minecraft:magma>, <minecraft:nether_brick>, <minecraft:magma>], [<minecraft:nether_brick>, <minecraft:glass>, <minecraft:nether_brick>]]);
recipes.addShaped(<minecraft:purpur_stairs> * 2, [[<minecraft:purpur_slab>, null, null],[<minecraft:purpur_slab>, <minecraft:purpur_slab>, null], [null, null, null]]);
recipes.addShaped(<minecraft:purpur_slab> * 6, [[null, null, null],[<minecraft:purpur_block>, <minecraft:purpur_block>, <minecraft:purpur_block>], [null, null, null]]);
furnace.addRecipe(<minecraft:purpur_pillar>, <minecraft:purpur_block>, 0.0);
furnace.addRecipe(<minecraft:end_bricks>, <minecraft:end_stone>, 0.0);
recipes.addShaped(<minecraft:red_sandstone_stairs> * 2, [[<minecraft:stone_slab2>, null, null],[<minecraft:stone_slab2>, <minecraft:stone_slab2>, null], [null, null, null]]);
recipes.addShaped(<minecraft:stone_slab2> * 6, [[null, null, null],[<minecraft:red_sandstone>, <minecraft:red_sandstone>, <minecraft:red_sandstone>], [null, null, null]]);
furnace.addRecipe(<minecraft:red_sandstone:2>, <minecraft:red_sandstone:1>, 0.0);
furnace.addRecipe(<minecraft:red_sandstone:1>, <minecraft:red_sandstone>, 0.0);
furnace.addRecipe(<minecraft:red_sandstone>, <minecraft:sand:1>, 0.0);
recipes.addShaped(<minecraft:hay_block>, [[<minecraft:wheat>, <minecraft:wheat>, <minecraft:wheat>],[<minecraft:wheat>, <minecraft:wheat>, <minecraft:wheat>], [<minecraft:wheat>, <minecraft:wheat>, <minecraft:wheat>]]);
recipes.addShaped(<minecraft:wheat> * 9, [[null, null, null],[null, <minecraft:hay_block>, null], [null, null, null]]);
furnace.addRecipe(<minecraft:prismarine:2>, <minecraft:prismarine:1>, 0.0);
furnace.addRecipe(<minecraft:prismarine:1>, <minecraft:prismarine>, 0.0);
recipes.addShaped(<minecraft:prismarine> * 2, [[null, <minecraft:prismarine_crystals>, null],[<minecraft:prismarine_crystals>, <minecraft:cobblestone>, <minecraft:prismarine_crystals>], [null, <minecraft:prismarine_crystals>, null]]);
recipes.addShaped(<minecraft:acacia_stairs> * 2, [[<minecraft:wooden_slab:4>, null, null],[<minecraft:wooden_slab:4>, <minecraft:wooden_slab:4>, null], [null, null, null]]);
recipes.addShaped(<minecraft:wooden_slab:4> * 6, [[null, null, null],[<minecraft:planks:4>, <minecraft:planks:4>, <minecraft:planks:4>], [null, null, null]]);
recipes.addShaped(<minecraft:planks:4> * 4, [[null, null, null],[null, <minecraft:log2>, null], [null, null, null]]);
recipes.addShaped(<minecraft:dark_oak_stairs> * 2, [[<minecraft:wooden_slab:5>, null, null],[<minecraft:wooden_slab:5>, <minecraft:wooden_slab:5>, null], [null, null, null]]);
recipes.addShaped(<minecraft:wooden_slab:5> * 6, [[null, null, null],[<minecraft:planks:5>, <minecraft:planks:5>, <minecraft:planks:5>], [null, null, null]]);
recipes.addShaped(<minecraft:planks:5> * 4, [[null, null, null],[null, <minecraft:log2:1>, null], [null, null, null]]);
recipes.addShaped(<minecraft:jungle_stairs> * 2, [[<minecraft:wooden_slab:3>, null, null],[<minecraft:wooden_slab:3>, <minecraft:wooden_slab:3>, null], [null, null, null]]);
recipes.addShaped(<minecraft:wooden_slab:3> * 6, [[null, null, null],[<minecraft:planks:3>, <minecraft:planks:3>, <minecraft:planks:3>], [null, null, null]]);
recipes.addShaped(<minecraft:planks:3> * 4, [[null, null, null],[null, <minecraft:log:3>, null], [null, null, null]]);
recipes.addShaped(<minecraft:birch_stairs> * 2, [[<minecraft:wooden_slab:2>, null, null],[<minecraft:wooden_slab:2>, <minecraft:wooden_slab:2>, null], [null, null, null]]);
recipes.addShaped(<minecraft:wooden_slab:2> * 6, [[null, null, null],[<minecraft:planks:2>, <minecraft:planks:2>, <minecraft:planks:2>], [null, null, null]]);
recipes.addShaped(<minecraft:planks:2> * 4, [[null, null, null],[null, <minecraft:log:2>, null], [null, null, null]]);
recipes.addShaped(<minecraft:spruce_stairs> * 2, [[<minecraft:wooden_slab:1>, null, null],[<minecraft:wooden_slab:1>, <minecraft:wooden_slab:1>, null], [null, null, null]]);
recipes.addShaped(<minecraft:wooden_slab:1> * 6, [[null, null, null],[<minecraft:planks:1>, <minecraft:planks:1>, <minecraft:planks:1>], [null, null, null]]);
recipes.addShaped(<minecraft:planks:1> * 4, [[null, null, null],[null, <minecraft:log:1>, null], [null, null, null]]);
recipes.addShaped(<minecraft:sea_lantern> * 2, [[null, <minecraft:prismarine_crystals>, null],[<minecraft:prismarine_crystals>, <minecraft:glowstone>, <minecraft:prismarine_crystals>], [null, <minecraft:prismarine_crystals>, null]]);
recipes.addShaped(<minecraft:prismarine_crystals> * 3, [[<minecraft:prismarine_shard>, <minecraft:prismarine_shard>, <minecraft:prismarine_shard>],[<minecraft:prismarine_shard>, <minecraft:prismarine_shard>, <minecraft:prismarine_shard>], [<minecraft:prismarine_shard>, <minecraft:prismarine_shard>, <minecraft:prismarine_shard>]]);
recipes.addShaped(<minecraft:lit_pumpkin>, [[null, null, null],[null, <minecraft:pumpkin>, null], [null, <minecraft:torch>, null]]);
recipes.addShaped(<minecraft:glowstone>, [[null, <minecraft:soul_sand>, null],[<minecraft:netherrack>, <minecraft:torch>, <minecraft:netherrack>], [null, <minecraft:soul_sand>, null]]);
recipes.addShaped(<minecraft:quartz_stairs> * 2, [[<minecraft:stone_slab:7>, null, null],[<minecraft:stone_slab:7>, <minecraft:stone_slab:7>, null], [null, null, null]]);
recipes.addShaped(<minecraft:stone_slab:7> * 6, [[null, null, null],[<minecraft:quartz_block>, <minecraft:quartz_block>, <minecraft:quartz_block>], [null, null, null]]);
furnace.addRecipe(<minecraft:quartz_block:2>, <minecraft:quartz_block:1>, 0.0);
furnace.addRecipe(<minecraft:quartz_block:1>, <minecraft:quartz_block>, 0.0);
recipes.addShaped(<minecraft:end_stone> * 2, [[<minecraft:sandstone:2>, <minecraft:quartz_block>, <minecraft:sandstone:2>],[<minecraft:netherrack>, <minecraft:sandstone:2>, <minecraft:netherrack>], [<minecraft:sandstone:2>, <minecraft:quartz_block>, <minecraft:sandstone:2>]]);
recipes.addShaped(<minecraft:melon> * 9, [[null, null, null],[null, <minecraft:melon_block>, null], [null, null, null]]);
recipes.addShaped(<minecraft:melon_block>, [[<minecraft:melon>, <minecraft:melon>, <minecraft:melon>],[<minecraft:melon>, <minecraft:melon>, <minecraft:melon>], [<minecraft:melon>, <minecraft:melon>, <minecraft:melon>]]);
recipes.addShaped(<minecraft:obsidian>, [[<minecraft:log>, <minecraft:potion>, <minecraft:log>],[<minecraft:log>, <minecraft:netherrack>, <minecraft:log>], [<minecraft:soul_sand>, <minecraft:magma>, <minecraft:soul_sand>]]);
recipes.addShaped(<minecraft:nether_brick_stairs>, [[<minecraft:stone_slab:6>, null, null],[<minecraft:stone_slab:6>, <minecraft:stone_slab:6>, null], [null, null, null]]);
recipes.addShaped(<minecraft:stone_slab:6> * 6, [[null, null, null],[<minecraft:nether_brick>, <minecraft:nether_brick>, <minecraft:nether_brick>], [null, null, null]]);
recipes.addShaped(<minecraft:nether_brick> * 6, [[<minecraft:netherrack>, <minecraft:netherrack>, <minecraft:netherrack>],[<minecraft:soul_sand>, <minecraft:egg>, <minecraft:soul_sand>], [<minecraft:netherrack>, <minecraft:netherrack>, <minecraft:netherrack>]]);
recipes.addShaped(<minecraft:soul_sand> * 5, [[<minecraft:sand>, <minecraft:netherrack>, <minecraft:sand>],[<minecraft:netherrack>, <minecraft:sand>, <minecraft:netherrack>], [<minecraft:sand>, <minecraft:netherrack>, <minecraft:sand>]]);
recipes.addShaped(<minecraft:netherrack> * 3, [[null, null, null],[<minecraft:cobblestone>, <minecraft:magma>, <minecraft:cobblestone>], [null, null, null]]);
recipes.addShaped(<minecraft:brick_stairs> * 2, [[<minecraft:stone_slab:4>, null, null],[<minecraft:stone_slab:4>, <minecraft:stone_slab:4>, null], [null, null, null]]);
recipes.addShaped(<minecraft:stone_slab:4> * 6, [[null, null, null],[<minecraft:brick_block>, <minecraft:brick_block>, <minecraft:brick_block>], [null, null, null]]);
recipes.addShaped(<minecraft:brick_block> * 6, [[<minecraft:stonebrick>, <minecraft:stonebrick>, <minecraft:stonebrick>],[<minecraft:sand>, <minecraft:egg>, <minecraft:sand>], [<minecraft:stonebrick>, <minecraft:stonebrick>, <minecraft:stonebrick>]]);
recipes.addShaped(<minecraft:stone_stairs> * 2, [[<minecraft:stone_slab:3>, null, null],[<minecraft:stone_slab:3>, <minecraft:stone_slab:3>, null], [null, null, null]]);
recipes.addShaped(<minecraft:stone_slab:3> * 6, [[null, null, null],[<minecraft:cobblestone>, <minecraft:cobblestone>, <minecraft:cobblestone>], [null, null, null]]);
recipes.addShaped(<minecraft:stone_slab:5> * 6, [[null, null, null],[<minecraft:stonebrick>, <minecraft:stonebrick>, <minecraft:stonebrick>], [null, null, null]]);
furnace.addRecipe(<minecraft:stonebrick:3>, <minecraft:stonebrick>, 0.0);
recipes.addShaped(<minecraft:stonebrick:2> * 9, [[<minecraft:stonebrick>, <minecraft:stonebrick>, <minecraft:stonebrick>],[<minecraft:stonebrick>, null, <minecraft:stonebrick>], [<minecraft:stonebrick>, <minecraft:stonebrick>, <minecraft:stonebrick>]]);
recipes.addShaped(<minecraft:stonebrick>, [[<minecraft:stone>, <minecraft:stone>, <minecraft:stone>],[<minecraft:stone>, <minecraft:stone>, <minecraft:stone>], [<minecraft:stone>, <minecraft:stone>, <minecraft:stone>]]);
recipes.addShaped(<minecraft:stone_slab> * 6, [[null, null, null],[<minecraft:stone>, <minecraft:stone>, <minecraft:stone>], [null, null, null]]);
recipes.addShaped(<minecraft:iron_ingot> * 9, [[null, null, null],[null, <minecraft:iron_block>, null], [null, null, null]]);
recipes.addShaped(<minecraft:iron_block>, [[<minecraft:iron_ingot>, <minecraft:iron_ingot>, <minecraft:iron_ingot>],[<minecraft:iron_ingot>, <minecraft:iron_ingot>, <minecraft:iron_ingot>], [<minecraft:iron_ingot>, <minecraft:iron_ingot>, <minecraft:iron_ingot>]]);
recipes.addShaped(<minecraft:gold_ingot> * 9, [[null, null, null],[null, <minecraft:gold_block>, null], [null, null, null]]);
recipes.addShaped(<minecraft:gold_block>, [[<minecraft:gold_ingot>, <minecraft:gold_ingot>, <minecraft:gold_ingot>],[<minecraft:gold_ingot>, <minecraft:gold_ingot>, <minecraft:gold_ingot>], [<minecraft:gold_ingot>, <minecraft:gold_ingot>, <minecraft:gold_ingot>]]);
recipes.addShaped(<minecraft:wool>, [[<minecraft:string>, null, <minecraft:string>],[null, <minecraft:string>, null], [<minecraft:string>, null, <minecraft:string>]]);
recipes.addShaped(<minecraft:oak_stairs> * 2, [[<minecraft:wooden_slab>, null, null],[<minecraft:wooden_slab>, <minecraft:wooden_slab>, null], [null, null, null]]);
recipes.addShaped(<minecraft:wooden_slab>, [[null, null, null],[<minecraft:planks>, <minecraft:planks>, <minecraft:planks>], [null, null, null]]);
recipes.addShaped(<minecraft:coal> * 32, [[null, null, null],[null, <minecraft:coal_block>, null], [null, null, null]]);
recipes.addShaped(<minecraft:dye:4> * 32, [[null, null, null],[null, <minecraft:lapis_block>, null], [null, null, null]]);
recipes.addShaped(<minecraft:log>, [[<minecraft:bookshelf>, <minecraft:bookshelf>, <minecraft:bookshelf>],[<minecraft:bookshelf>, <minecraft:bookshelf>, <minecraft:bookshelf>], [<minecraft:bookshelf>, <minecraft:bookshelf>, <minecraft:bookshelf>]]);
recipes.addShaped(<minecraft:bookshelf>, [[<minecraft:planks>, <minecraft:planks>, <minecraft:planks>],[<minecraft:planks>, <minecraft:planks>, <minecraft:planks>], [<minecraft:planks>, <minecraft:planks>, <minecraft:planks>]]);
recipes.addShaped(<minecraft:sandstone>, [[<minecraft:sand>, <minecraft:sand>, null],[<minecraft:sand>, <minecraft:sand>, null], [null, null, null]]);
furnace.addRecipe(<minecraft:sandstone:2>, <minecraft:sandstone:1>, 0.0);
furnace.addRecipe(<minecraft:sandstone:1>, <minecraft:sandstone>, 0.0);
furnace.addRecipe(<minecraft:coal_block>, <minecraft:coal_ore>, 0.0);
furnace.addRecipe(<minecraft:lapis_block>, <minecraft:lapis_ore>, 0.0);
furnace.addRecipe(<minecraft:iron_ingot>, <minecraft:iron_ore>, 0.0);
furnace.addRecipe(<minecraft:gold_ingot>, <minecraft:gold_ore>, 0.0);
furnace.addRecipe(<minecraft:sand:1>, <minecraft:gravel>, 0.0);
furnace.addRecipe(<minecraft:dirt:2>, <minecraft:dirt:1>, 0.0);
furnace.addRecipe(<minecraft:dirt:1>, <minecraft:dirt>, 0.0);
furnace.addRecipe(<minecraft:stone:6>, <minecraft:stone:5>, 0.0);
furnace.addRecipe(<minecraft:stone:4>, <minecraft:stone:3>, 0.0);
furnace.addRecipe(<minecraft:stone:2>, <minecraft:stone:1>, 0.0);
furnace.addRecipe(<minecraft:magma>, <minecraft:stone>, 0.0);
furnace.addRecipe(<minecraft:stone>, <minecraft:cobblestone>, 0.0);
furnace.addRecipe(<minecraft:cooked_porkchop>, <minecraft:porkchop>, 0.0);
furnace.addRecipe(<minecraft:cooked_fish:1>, <minecraft:fish>, 0.0);
furnace.addRecipe(<minecraft:cooked_fish:1>, <minecraft:fish:1>, 0.0);
furnace.addRecipe(<minecraft:cooked_fish:1>, <minecraft:fish:2>, 0.0);
furnace.addRecipe(<minecraft:cooked_fish:1>, <minecraft:fish:3>, 0.0);
furnace.addRecipe(<minecraft:bone>, <minecraft:rotten_flesh>, 0.0);
furnace.addRecipe(<minecraft:cooked_beef>, <minecraft:beef>, 0.0);
furnace.addRecipe(<minecraft:cooked_chicken>, <minecraft:chicken>, 0.0);
furnace.addRecipe(<minecraft:baked_potato>, <minecraft:potato>, 0.0);
furnace.addRecipe(<minecraft:cooked_rabbit>, <minecraft:rabbit>, 0.0);
furnace.addRecipe(<minecraft:cooked_mutton>, <minecraft:mutton>, 0.0);
furnace.addRecipe(<minecraft:prismarine_shard>, <minecraft:quartz>, 0.0);
furnace.addRecipe(<minecraft:quartz>, <minecraft:glass>, 0.0);
furnace.addRecipe(<minecraft:coal:1>, <minecraft:log>, 0.0);
furnace.addRecipe(<minecraft:glass>, <minecraft:sand>, 0.0);
//File End
